import { Product, Category, User, Seller } from '@/types';

export const categories = [
  {
    id: '1',
    name: 'Vegetables & Fruits',
    slug: 'vegetables-fruits',
    description: 'Fresh vegetables and fruits',
    image: '/category-images/vegetable.png', 
    subcategories: [], // No specific subcategories provided for these new categories, so keeping it empty
  },
  {
    id: '2',
    name: 'Dairy & Breakfast',
    slug: 'dairy-breakfast',
    description: 'Milk, cheese, yogurt, and breakfast essentials',
    image: '/category-images/dairy_breakfast.png', 
    subcategories: [],
  },
  {
    id: '3',
    name: 'Chips & Namkeen',
    slug: 'chips-namkeen',
    description: 'Snacks and savory delights',
    image: '/category-images/munchies.png', 
    subcategories: [],
  },
  {
    id: '4',
    name: 'Cold Drinks & Juices',
    slug: 'cold-drinks-juices',
    description: 'Refreshing beverages and natural juices',
    image: '/category-images/cold_and_juices.png', 
    subcategories: [],
  },
  {
    id: '5',
    name: 'Instant & Frozen',
    slug: 'instant-frozen',
    description: 'Quick meals and frozen foods',
    image: '/category-images/instant.png', 
    subcategories: [],
  },
  {
    id: '6',
    name: 'Tea Coffee & Health',
    slug: 'tea-coffee-health',
    description: 'Hot beverages and health drinks',
    image: '/category-images/tea_coffee.png', 
    subcategories: [],
  },
  {
    id: '7',
    name: 'Bakery & Biscuits',
    slug: 'bakery-biscuits',
    description: 'Freshly baked goods and various biscuits',
    image: '/category-images/bakery_biscuits.png', 
    subcategories: [],
  },
  {
    id: '8',
    name: 'Sweet Tooth',
    slug: 'sweet-tooth',
    description: 'Chocolates, candies, and desserts',
    image: '/category-images/sweet_tooth.png', 
    subcategories: [],
  },
  {
    id: '9',
    name: 'Atta Rice & Dal',
    slug: 'atta-rice-dal',
    description: 'Staple grains and pulses',
    image: '/category-images/atta_rice.png', 
    subcategories: [],
  },
  {
    id: '10',
    name: 'Dry Fruits Masala & Oil',
    slug: 'dry-fruits-masala-oil',
    description: 'Nuts, spices, and cooking oils',
    image: '/category-images/dry_masala.png', 
    subcategories: [],
  },
  {
    id: '11',
    name: 'Sauces & Spreads',
    slug: 'sauces-spreads',
    description: 'Condiments and delicious spreads',
    image: '/category-images/sauce_spreads.png', 
    subcategories: [],
  },
  {
    id: '12',
    name: 'Chicken Meat & Fish',
    slug: 'chicken-meat-fish',
    description: 'Fresh poultry, meat, and seafood',
    image: '/category-images/chicken_meat.png', 
    subcategories: [],
  },
  {
    id: '13',
    name: 'Pan Corner Treats',
    slug: 'pan-corner-treats',
    description: 'Traditional Indian mouth fresheners',
    image: '/category-images/paan_corner.png', 
    subcategories: [],
  },
  {
    id: '14',
    name: 'Organic & Premium',
    slug: 'organic-premium',
    description: 'High-quality organic products',
    image: '/category-images/organic_premium.png', 
    subcategories: [],
  },
  {
    id: '15',
    name: 'Baby Care Essentials',
    slug: 'baby-care-essentials',
    description: 'Products for baby care',
    image: '/category-images/baby_care.png', 
    subcategories: [],
  },
  {
    id: '16',
    name: 'Pharma & Wellness',
    slug: 'pharma-wellness',
    description: 'Health and pharmaceutical products',
    image: '/category-images/pharma_wellness.png', 
    subcategories: [],
  },
  {
    id: '17',
    name: 'Cleaning Essential',
    slug: 'cleaning-essential',
    description: 'Household cleaning supplies',
    image: '/category-images/cleaning.png', 
    subcategories: [],
  },
  {
    id: '18',
    name: 'Home & Office',
    slug: 'home-office',
    description: 'Supplies for home and office',
    image: '/category-images/home_office.png', 
    subcategories: [],
  },
  {
    id: '19',
    name: 'Personal Care',
    slug: 'personal-care',
    description: 'Products for personal hygiene and grooming',
    image: '/category-images/personal_care.png', 
    subcategories: [],
  },
  {
    id: '20',
    name: 'Pet Care Essential',
    slug: 'pet-care-essential',
    description: 'Everything for your beloved pets',
    image: '/category-images/pet_care.png', 
    subcategories: [],
  },
];


export const products: Product[] = [
  {
    adminUid: "suPbGytrYMSTPyPaPowTK2uQ3gi1",
    itemCount: 0,
    productCategory: "Dry Fruits Masala & Oil",
    productId: "Zq0Dit4xBl1JEKUXOeNc53S1j",
    productImageUris: [
"https://firebasestorage.googleapis.com/v0/b/plexify-6469a.firebasestorage.app/o/suPbGytrYMSTPyPaPowTK2uQ3gi1%2Fimages%2F411745b3-c054-42a2-bf7f-33c9603227a6?alt=media&token=5fb8640d-026b-4ce7-af40-fde2aaf0de51",
"https://firebasestorage.googleapis.com/v0/b/plexify-6469a.firebasestorage.app/o/suPbGytrYMSTPyPaPowTK2uQ3gi1%2Fimages%2F917abe7a-23f7-4514-ad14-dfccf260ea77?alt=media&token=12ade941-637a-4cce-bcfc-9c3452561af0",
"https://firebasestorage.googleapis.com/v0/b/plexify-6469a.firebasestorage.app/o/suPbGytrYMSTPyPaPowTK2uQ3gi1%2Fimages%2F19b843a5-735c-4e5e-b96a-78aa3d84fda1?alt=media&token=2a3caef3-fb48-493f-8cda-55319f527ab9",
"https://firebasestorage.googleapis.com/v0/b/plexify-6469a.firebasestorage.app/o/suPbGytrYMSTPyPaPowTK2uQ3gi1%2Fimages%2F17ed9c0d-0756-4da6-81e8-062f07fb21ed?alt=media&token=c624327a-2064-4948-a545-468e18411ee1"
    ],
    productPrice: 240,
    productQuantity: 1,
    productRandomId: "3IbNeqWT5vq9Nd220eVtLx5qU",
    productStock: 48,
    productTitle: "Oil",
    productType: "Cooking Oil",
    productUnit: "Ltr",
  },
  {
    adminUid: "suPbGytrYMSTPyPaPowTK2uQ3gi1",
    itemCount: 0,
    productCategory: "Dairy & Breakfast",
    productId: "WExzVbdE7X5UYkM763k9VraO5",
    productImageUris: [
      'https://firebasestorage.googleapis.com/v0/b/plexify-6469a.firebasestorage.app/o/suPbGytrYMSTPyPaPowTK2uQ3gi1%2Fimages%2F204a60dc-3c70-460c-ac47-ea6426495397?alt=media&token=b9ff352b-97f0-4faa-a256-ee3f3a112f87'
    ],
    productPrice: 125,
    productQuantity: 1,
    productRandomId: "5D2bAaMhonHSVnLnVncB05mbR",
    productStock: 164,
    productTitle: "Amul Milk",
    productType: "Milk, Curd & Paneer",
    productUnit: "Ltr",
  },
  {
    adminUid: "suPbGytrYMSTPyPaPowTK2uQ3gi1",
    itemCount: 0,
    productCategory: "Atta Rice & Dal",
    productId: "2JDKrAHHELFI3L5thBICth4RC",
    productImageUris: [
      'https://firebasestorage.googleapis.com/v0/b/plexify-6469a.firebasestorage.app/o/suPbGytrYMSTPyPaPowTK2uQ3gi1%2Fimages%2F7f582519-69e1-4830-8682-8bf08ccb50ea?alt=media&token=5161bdf3-4089-4eb8-bbf1-d3e616c5905c'
    ],
    productPrice: 130,
    productQuantity: 1,
    productRandomId: "hngwkJj7ic3msLeLASP5IUyp3",
    productStock: 55,
    productTitle: "Atta",
    productType: "Atta & Rice",
    productUnit: "kg",
  },
  {
    adminUid: "suPbGytrYMSTPyPaPowTK2uQ3gi1",
    itemCount: 0,
    productCategory: "Atta Rice & Dal",
    productId: "yK3nwUFsF2UcTkbUDDl4ROYLI",
    productImageUris: [
      'https://firebasestorage.googleapis.com/v0/b/plexify-6469a.firebasestorage.app/o/suPbGytrYMSTPyPaPowTK2uQ3gi1%2Fimages%2F8f0dbbac-666a-43b0-9574-449dbdb1a33f?alt=media&token=2ca3984e-f590-4cb1-9ee0-851f517061a6'
    ],
    productPrice: 150,
    productQuantity: 1,
    productRandomId: "uew9EPgYsDe9q8rBw8Cv9Jw8j",
    productStock: 24,
    productTitle: "Rice",
    productType: "Atta & Rice",
    productUnit: "kg",
  },
];
export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
  addresses: [
    {
      id: '1',
      name: 'Home',
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      isDefault: true,
    },
  ],
  orders: [],
  wishlist: ['1', '3'],
  createdAt: '2024-01-01T10:00:00Z',
};

export const mockSeller: Seller = {
  id: 'seller1',
  name: 'Jane Smith',
  email: 'seller@example.com',
  businessName: 'TechWorld Store',
  businessAddress: '456 Business Ave, San Francisco, CA 94102',
  phone: '+1 (555) 987-6543',
  avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150',
  description: 'Leading retailer of premium electronics and gadgets with over 10 years of experience.',
  rating: 4.8,
  totalSales: 15420,
  products: ['1', '2'],
  isVerified: true,
  createdAt: '2023-06-15T10:00:00Z',
};