import { Product, Category, User, Seller } from '@/types';

export const categories = [
  {
    id: '1',
    name: 'Vegetables & Fruits',
    slug: 'vegetables-fruits',
    description: 'Fresh vegetables and fruits',
    image: '/category-images/vegetable.png', 
    subcategories: [], // No specific subcategories provided for these new categories, so keeping it empty
  },
  {
    id: '2',
    name: 'Dairy & Breakfast',
    slug: 'dairy-breakfast',
    description: 'Milk, cheese, yogurt, and breakfast essentials',
    image: '/category-images/dairy_breakfast.png', 
    subcategories: [],
  },
  {
    id: '3',
    name: 'Chips & Namkeen',
    slug: 'chips-namkeen',
    description: 'Snacks and savory delights',
    image: '/category-images/munchies.png', 
    subcategories: [],
  },
  {
    id: '4',
    name: 'Cold Drinks & Juices',
    slug: 'cold-drinks-juices',
    description: 'Refreshing beverages and natural juices',
    image: '/category-images/cold_and_juices.png', 
    subcategories: [],
  },
  {
    id: '5',
    name: 'Instant & Frozen',
    slug: 'instant-frozen',
    description: 'Quick meals and frozen foods',
    image: '/category-images/instant.png', 
    subcategories: [],
  },
  {
    id: '6',
    name: 'Tea Coffee & Health',
    slug: 'tea-coffee-health',
    description: 'Hot beverages and health drinks',
    image: '/category-images/tea_coffee.png', 
    subcategories: [],
  },
  {
    id: '7',
    name: 'Bakery & Biscuits',
    slug: 'bakery-biscuits',
    description: 'Freshly baked goods and various biscuits',
    image: '/category-images/bakery_biscuits.png', 
    subcategories: [],
  },
  {
    id: '8',
    name: 'Sweet Tooth',
    slug: 'sweet-tooth',
    description: 'Chocolates, candies, and desserts',
    image: '/category-images/sweet_tooth.png', 
    subcategories: [],
  },
  {
    id: '9',
    name: 'Atta Rice & Dal',
    slug: 'atta-rice-dal',
    description: 'Staple grains and pulses',
    image: '/category-images/atta_rice.png', 
    subcategories: [],
  },
  {
    id: '10',
    name: 'Dry Fruits Masala & Oil',
    slug: 'dry-fruits-masala-oil',
    description: 'Nuts, spices, and cooking oils',
    image: '/category-images/dry_masala.png', 
    subcategories: [],
  },
  {
    id: '11',
    name: 'Sauces & Spreads',
    slug: 'sauces-spreads',
    description: 'Condiments and delicious spreads',
    image: '/category-images/sauce_spreads.png', 
    subcategories: [],
  },
  {
    id: '12',
    name: 'Chicken Meat & Fish',
    slug: 'chicken-meat-fish',
    description: 'Fresh poultry, meat, and seafood',
    image: '/category-images/chicken_meat.png', 
    subcategories: [],
  },
  {
    id: '13',
    name: 'Pan Corner Treats',
    slug: 'pan-corner-treats',
    description: 'Traditional Indian mouth fresheners',
    image: '/category-images/paan_corner.png', 
    subcategories: [],
  },
  {
    id: '14',
    name: 'Organic & Premium',
    slug: 'organic-premium',
    description: 'High-quality organic products',
    image: '/category-images/organic_premium.png', 
    subcategories: [],
  },
  {
    id: '15',
    name: 'Baby Care Essentials',
    slug: 'baby-care-essentials',
    description: 'Products for baby care',
    image: '/category-images/baby_care.png', 
    subcategories: [],
  },
  {
    id: '16',
    name: 'Pharma & Wellness',
    slug: 'pharma-wellness',
    description: 'Health and pharmaceutical products',
    image: '/category-images/pharma_wellness.png', 
    subcategories: [],
  },
  {
    id: '17',
    name: 'Cleaning Essential',
    slug: 'cleaning-essential',
    description: 'Household cleaning supplies',
    image: '/category-images/cleaning.png', 
    subcategories: [],
  },
  {
    id: '18',
    name: 'Home & Office',
    slug: 'home-office',
    description: 'Supplies for home and office',
    image: '/category-images/home_office.png', 
    subcategories: [],
  },
  {
    id: '19',
    name: 'Personal Care',
    slug: 'personal-care',
    description: 'Products for personal hygiene and grooming',
    image: '/category-images/personal_care.png', 
    subcategories: [],
  },
  {
    id: '20',
    name: 'Pet Care Essential',
    slug: 'pet-care-essential',
    description: 'Everything for your beloved pets',
    image: '/category-images/pet_care.png', 
    subcategories: [],
  },
];


export const products: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro',
    price: 999,
    originalPrice: 1099,
    description: 'The latest iPhone with advanced features and stunning design. Experience the power of A17 Pro chip.',
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1616470/pexels-photo-1616470.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Apple',
    rating: 4.8,
    reviews: 2450,
    inStock: true,
    stockQuantity: 50,
    features: ['A17 Pro chip', '48MP camera system', 'Titanium design', 'Action Button'],
    specifications: {
      'Display': '6.1-inch Super Retina XDR',
      'Storage': '128GB, 256GB, 512GB, 1TB',
      'Camera': '48MP Main, 12MP Ultra Wide, 12MP Telephoto',
      'Battery': 'Up to 23 hours video playback',
    },
    tags: ['smartphone', 'apple', 'premium', 'camera'],
    sellerId: 'seller1',
    sellerName: 'TechWorld Store',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'MacBook Pro 14"',
    price: 1999,
    description: 'Professional laptop with M3 chip for incredible performance and all-day battery life.',
    image: 'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    rating: 4.7,
    reviews: 1890,
    inStock: true,
    stockQuantity: 25,
    features: ['M3 chip', '14-inch Liquid Retina XDR display', 'Up to 22 hours battery', 'Three Thunderbolt 4 ports'],
    specifications: {
      'Processor': 'Apple M3 chip',
      'Memory': '8GB, 16GB, 24GB, 32GB',
      'Storage': '512GB, 1TB, 2TB, 4TB, 8TB',
      'Display': '14.2-inch Liquid Retina XDR',
    },
    tags: ['laptop', 'apple', 'professional', 'performance'],
    sellerId: 'seller1',
    sellerName: 'TechWorld Store',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '3',
    name: 'Sony WH-1000XM5',
    price: 299,
    originalPrice: 399,
    description: 'Industry-leading noise canceling headphones with exceptional sound quality.',
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Sony',
    rating: 4.6,
    reviews: 3200,
    inStock: true,
    stockQuantity: 75,
    features: ['Industry-leading noise canceling', '30-hour battery life', 'Quick charge', 'Speak-to-chat'],
    specifications: {
      'Driver': '30mm',
      'Frequency Response': '4Hz-40kHz',
      'Battery Life': '30 hours',
      'Charging': 'USB-C, Quick charge',
    },
    tags: ['headphones', 'sony', 'wireless', 'noise-canceling'],
    sellerId: 'seller2',
    sellerName: 'AudioMax Electronics',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '4',
    name: 'Canon EOS R5',
    price: 3899,
    description: 'Professional full-frame mirrorless camera with 45MP sensor and 8K video recording.',
    image: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Cameras',
    brand: 'Canon',
    rating: 4.9,
    reviews: 845,
    inStock: true,
    stockQuantity: 15,
    features: ['45MP full-frame sensor', '8K video recording', 'In-body stabilization', 'Dual pixel CMOS AF'],
    specifications: {
      'Sensor': '45MP Full-frame CMOS',
      'Video': '8K RAW, 4K 120p',
      'ISO Range': '100-51200',
      'Autofocus': '1053 AF points',
    },
    tags: ['camera', 'canon', 'professional', 'photography'],
    sellerId: 'seller3',
    sellerName: 'PhotoPro Gear',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '5',
    name: 'Premium Cotton T-Shirt',
    price: 29,
    originalPrice: 39,
    description: 'Comfortable and stylish cotton t-shirt perfect for everyday wear.',
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Fashion',
    subcategory: 'Men\'s Clothing',
    brand: 'StyleCo',
    rating: 4.3,
    reviews: 567,
    inStock: true,
    stockQuantity: 200,
    features: ['100% cotton', 'Pre-shrunk', 'Comfortable fit', 'Machine washable'],
    specifications: {
      'Material': '100% Cotton',
      'Sizes': 'XS, S, M, L, XL, XXL',
      'Colors': 'White, Black, Navy, Gray',
      'Care': 'Machine wash cold',
    },
    tags: ['t-shirt', 'cotton', 'casual', 'comfortable'],
    sellerId: 'seller4',
    sellerName: 'Fashion Forward',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '6',
    name: 'Wireless Bluetooth Speaker',
    price: 79,
    originalPrice: 99,
    description: 'Portable speaker with rich sound and long battery life.',
    image: 'https://images.pexels.com/photos/1037999/pexels-photo-1037999.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1037999/pexels-photo-1037999.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'SoundTech',
    rating: 4.4,
    reviews: 1234,
    inStock: true,
    stockQuantity: 89,
    features: ['Bluetooth 5.0', '12-hour battery', 'Water resistant', 'Built-in microphone'],
    specifications: {
      'Connectivity': 'Bluetooth 5.0',
      'Battery': '12 hours playback',
      'Water Resistance': 'IPX7',
      'Dimensions': '7.9 x 2.8 x 2.8 inches',
    },
    tags: ['speaker', 'bluetooth', 'portable', 'wireless'],
    sellerId: 'seller2',
    sellerName: 'AudioMax Electronics',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
];

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
  addresses: [
    {
      id: '1',
      name: 'Home',
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      isDefault: true,
    },
  ],
  orders: [],
  wishlist: ['1', '3'],
  createdAt: '2024-01-01T10:00:00Z',
};

export const mockSeller: Seller = {
  id: 'seller1',
  name: 'Jane Smith',
  email: 'seller@example.com',
  businessName: 'TechWorld Store',
  businessAddress: '456 Business Ave, San Francisco, CA 94102',
  phone: '+1 (555) 987-6543',
  avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150',
  description: 'Leading retailer of premium electronics and gadgets with over 10 years of experience.',
  rating: 4.8,
  totalSales: 15420,
  products: ['1', '2'],
  isVerified: true,
  createdAt: '2023-06-15T10:00:00Z',
};