import { Product, Category, User, Seller } from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest gadgets and electronic devices',
    image: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=800',
    subcategories: [
      { id: '1', name: 'Smartphones', slug: 'smartphones', description: 'Latest mobile phones' },
      { id: '2', name: 'Laptops', slug: 'laptops', description: 'Computers and laptops' },
      { id: '3', name: 'Headphones', slug: 'headphones', description: 'Audio devices' },
      { id: '4', name: 'Cameras', slug: 'cameras', description: 'Photography equipment' },
    ],
  },
  {
    id: '2',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Trendy clothing and accessories',
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=800',
    subcategories: [
      { id: '5', name: 'Men\'s Clothing', slug: 'mens-clothing', description: 'Men\'s fashion' },
      { id: '6', name: 'Women\'s Clothing', slug: 'womens-clothing', description: 'Women\'s fashion' },
      { id: '7', name: 'Shoes', slug: 'shoes', description: 'Footwear for all' },
      { id: '8', name: 'Accessories', slug: 'accessories', description: 'Fashion accessories' },
    ],
  },
  {
    id: '3',
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Everything for your home',
    image: 'https://images.pexels.com/photos/1080696/pexels-photo-1080696.jpeg?auto=compress&cs=tinysrgb&w=800',
    subcategories: [
      { id: '9', name: 'Furniture', slug: 'furniture', description: 'Home furniture' },
      { id: '10', name: 'Decor', slug: 'decor', description: 'Home decorations' },
      { id: '11', name: 'Kitchen', slug: 'kitchen', description: 'Kitchen appliances' },
      { id: '12', name: 'Garden', slug: 'garden', description: 'Gardening supplies' },
    ],
  },
  {
    id: '4',
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description: 'Gear for active lifestyle',
    image: 'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg?auto=compress&cs=tinysrgb&w=800',
    subcategories: [
      { id: '13', name: 'Fitness', slug: 'fitness', description: 'Fitness equipment' },
      { id: '14', name: 'Outdoor Gear', slug: 'outdoor-gear', description: 'Outdoor equipment' },
      { id: '15', name: 'Sports Equipment', slug: 'sports-equipment', description: 'Sports gear' },
    ],
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro',
    price: 999,
    originalPrice: 1099,
    description: 'The latest iPhone with advanced features and stunning design. Experience the power of A17 Pro chip.',
    image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1616470/pexels-photo-1616470.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Apple',
    rating: 4.8,
    reviews: 2450,
    inStock: true,
    stockQuantity: 50,
    features: ['A17 Pro chip', '48MP camera system', 'Titanium design', 'Action Button'],
    specifications: {
      'Display': '6.1-inch Super Retina XDR',
      'Storage': '128GB, 256GB, 512GB, 1TB',
      'Camera': '48MP Main, 12MP Ultra Wide, 12MP Telephoto',
      'Battery': 'Up to 23 hours video playback',
    },
    tags: ['smartphone', 'apple', 'premium', 'camera'],
    sellerId: 'seller1',
    sellerName: 'TechWorld Store',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'MacBook Pro 14"',
    price: 1999,
    description: 'Professional laptop with M3 chip for incredible performance and all-day battery life.',
    image: 'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1029757/pexels-photo-1029757.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    rating: 4.7,
    reviews: 1890,
    inStock: true,
    stockQuantity: 25,
    features: ['M3 chip', '14-inch Liquid Retina XDR display', 'Up to 22 hours battery', 'Three Thunderbolt 4 ports'],
    specifications: {
      'Processor': 'Apple M3 chip',
      'Memory': '8GB, 16GB, 24GB, 32GB',
      'Storage': '512GB, 1TB, 2TB, 4TB, 8TB',
      'Display': '14.2-inch Liquid Retina XDR',
    },
    tags: ['laptop', 'apple', 'professional', 'performance'],
    sellerId: 'seller1',
    sellerName: 'TechWorld Store',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '3',
    name: 'Sony WH-1000XM5',
    price: 299,
    originalPrice: 399,
    description: 'Industry-leading noise canceling headphones with exceptional sound quality.',
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'Sony',
    rating: 4.6,
    reviews: 3200,
    inStock: true,
    stockQuantity: 75,
    features: ['Industry-leading noise canceling', '30-hour battery life', 'Quick charge', 'Speak-to-chat'],
    specifications: {
      'Driver': '30mm',
      'Frequency Response': '4Hz-40kHz',
      'Battery Life': '30 hours',
      'Charging': 'USB-C, Quick charge',
    },
    tags: ['headphones', 'sony', 'wireless', 'noise-canceling'],
    sellerId: 'seller2',
    sellerName: 'AudioMax Electronics',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '4',
    name: 'Canon EOS R5',
    price: 3899,
    description: 'Professional full-frame mirrorless camera with 45MP sensor and 8K video recording.',
    image: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Cameras',
    brand: 'Canon',
    rating: 4.9,
    reviews: 845,
    inStock: true,
    stockQuantity: 15,
    features: ['45MP full-frame sensor', '8K video recording', 'In-body stabilization', 'Dual pixel CMOS AF'],
    specifications: {
      'Sensor': '45MP Full-frame CMOS',
      'Video': '8K RAW, 4K 120p',
      'ISO Range': '100-51200',
      'Autofocus': '1053 AF points',
    },
    tags: ['camera', 'canon', 'professional', 'photography'],
    sellerId: 'seller3',
    sellerName: 'PhotoPro Gear',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '5',
    name: 'Premium Cotton T-Shirt',
    price: 29,
    originalPrice: 39,
    description: 'Comfortable and stylish cotton t-shirt perfect for everyday wear.',
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Fashion',
    subcategory: 'Men\'s Clothing',
    brand: 'StyleCo',
    rating: 4.3,
    reviews: 567,
    inStock: true,
    stockQuantity: 200,
    features: ['100% cotton', 'Pre-shrunk', 'Comfortable fit', 'Machine washable'],
    specifications: {
      'Material': '100% Cotton',
      'Sizes': 'XS, S, M, L, XL, XXL',
      'Colors': 'White, Black, Navy, Gray',
      'Care': 'Machine wash cold',
    },
    tags: ['t-shirt', 'cotton', 'casual', 'comfortable'],
    sellerId: 'seller4',
    sellerName: 'Fashion Forward',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '6',
    name: 'Wireless Bluetooth Speaker',
    price: 79,
    originalPrice: 99,
    description: 'Portable speaker with rich sound and long battery life.',
    image: 'https://images.pexels.com/photos/1037999/pexels-photo-1037999.jpeg?auto=compress&cs=tinysrgb&w=800',
    images: [
      'https://images.pexels.com/photos/1037999/pexels-photo-1037999.jpeg?auto=compress&cs=tinysrgb&w=800',
      'https://images.pexels.com/photos/1619651/pexels-photo-1619651.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'SoundTech',
    rating: 4.4,
    reviews: 1234,
    inStock: true,
    stockQuantity: 89,
    features: ['Bluetooth 5.0', '12-hour battery', 'Water resistant', 'Built-in microphone'],
    specifications: {
      'Connectivity': 'Bluetooth 5.0',
      'Battery': '12 hours playback',
      'Water Resistance': 'IPX7',
      'Dimensions': '7.9 x 2.8 x 2.8 inches',
    },
    tags: ['speaker', 'bluetooth', 'portable', 'wireless'],
    sellerId: 'seller2',
    sellerName: 'AudioMax Electronics',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
];

export const mockUser: User = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150',
  addresses: [
    {
      id: '1',
      name: 'Home',
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
      isDefault: true,
    },
  ],
  orders: [],
  wishlist: ['1', '3'],
  createdAt: '2024-01-01T10:00:00Z',
};

export const mockSeller: Seller = {
  id: 'seller1',
  name: 'Jane Smith',
  email: 'seller@example.com',
  businessName: 'TechWorld Store',
  businessAddress: '456 Business Ave, San Francisco, CA 94102',
  phone: '+1 (555) 987-6543',
  avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150',
  description: 'Leading retailer of premium electronics and gadgets with over 10 years of experience.',
  rating: 4.8,
  totalSales: 15420,
  products: ['1', '2'],
  isVerified: true,
  createdAt: '2023-06-15T10:00:00Z',
};